name: elparchee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  http: ^1.2.0
  video_player: ^2.8.6
=======
  video_player: ^2.8.2
  http: ^1.2.0
>>>>>>> 7304c93fdbe9dfe78f20d92113e26df571a5c729

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Agrega esta sección para que cargue tus videos e imágenes correctamente
  assets:
    - assets/videos/
<<<<<<< HEAD
    - assets/images/
=======
>>>>>>> 7304c93fdbe9dfe78f20d92113e26df571a5c729
