name: parche
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  http: ^1.2.0  # <-- Añadida esta dependencia
=======
  video_player: ^2.8.2  
>>>>>>> 0316c6c (Actualización de código y nuevos assets)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
<<<<<<< HEAD
  uses-material-design: true
=======
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
>>>>>>> 0316c6c (Actualización de código y nuevos assets)
